
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const SIGNING_IN_TO_PURCHASE = 'SIGNING_IN_TO_PURCHASE';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_ALL_CART_ITEMS = 'REMOVE_ALL_CART_ITEMS';



export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS';
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const PURCHASE_ITEMS_START = 'PURCHASE_ITEMS_START';
export const PURCHASE_ITEMS_SUCCESS = 'PURCHASE_ITEMS_SUCCESS';
export const PURCHASE_ITEMS_FAIL = 'PURCHASE_ITEMS_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const NOTIFY_ADMIN_OF_CHAT = 'NOTIFY_ADMIN_OF_CHAT';
export const FETCH_USER_CHATS = 'FETCH_USER_CHATS';
export const FETCH_USER_CHATS_SUCCESS = 'FETCH_USER_CHATS_SUCCESS';

